// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trainer.Data;

#nullable disable

namespace Trainer.Data.Migrations
{
    [DbContext(typeof(TrainerDbContext))]
    [Migration("20261001203805_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.31");

            modelBuilder.Entity("Trainer.Core.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("AvgCadence")
                        .HasColumnType("REAL");

                    b.Property<double?>("AvgHr")
                        .HasColumnType("REAL");

                    b.Property<double?>("AvgPower")
                        .HasColumnType("REAL");

                    b.Property<double?>("DistanceKm")
                        .HasColumnType("REAL");

                    b.Property<int>("DurationSec")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HrBasedTss")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("IntensityFactor")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("NormalizedPower")
                        .HasColumnType("REAL");

                    b.Property<int?>("PlannedWorkoutId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PowerCurve")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<long?>("StravaId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Tss")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("StartTime");

                    b.HasIndex("StravaId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("Trainer.Core.Models.Athlete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DefaultIndoor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EdgePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LongRideDay")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NoRaceGoal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PlanAnchor")
                        .HasColumnType("TEXT");

                    b.Property<string>("StravaAccessToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("StravaClientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StravaClientSecret")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StravaLastSyncUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("StravaRefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StravaTokenExpiresUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ThresholdHr")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrainingDays")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WatchFolder")
                        .HasColumnType("TEXT");

                    b.Property<double>("WeeklyHours")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Athletes");
                });

            modelBuilder.Entity("Trainer.Core.Models.BlockedDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("BlockedDays");
                });

            modelBuilder.Entity("Trainer.Core.Models.DailyLoad", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double>("Atl")
                        .HasColumnType("REAL");

                    b.Property<double>("Ctl")
                        .HasColumnType("REAL");

                    b.Property<double>("Tsb")
                        .HasColumnType("REAL");

                    b.Property<double>("Tss")
                        .HasColumnType("REAL");

                    b.HasKey("Date");

                    b.ToTable("DailyLoads");
                });

            modelBuilder.Entity("Trainer.Core.Models.FtpEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Watts")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.ToTable("FtpHistory", (string)null);
                });

            modelBuilder.Entity("Trainer.Core.Models.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TargetRaceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("Trainer.Core.Models.PlanWeek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlanId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PlannedCtl")
                        .HasColumnType("REAL");

                    b.Property<int?>("RaceId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TargetHours")
                        .HasColumnType("REAL");

                    b.Property<double>("TargetTss")
                        .HasColumnType("REAL");

                    b.Property<DateOnly>("WeekStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("WeekType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("PlanWeeks");
                });

            modelBuilder.Entity("Trainer.Core.Models.PlannedWorkout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationSec")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Indoor")
                        .HasColumnType("INTEGER");

                    b.Property<double>("IntensityFactor")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Locked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Steps")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Superseded")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Tss")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Date", "Superseded");

                    b.ToTable("PlannedWorkouts");
                });

            modelBuilder.Entity("Trainer.Core.Models.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double>("DurationHours")
                        .HasColumnType("REAL");

                    b.Property<int>("Intensity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("Trainer.Core.Models.WorkoutTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaxLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MinLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Steps")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Intervals");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("WorkoutTemplates");
                });

            modelBuilder.Entity("Trainer.Core.Models.PlanWeek", b =>
                {
                    b.HasOne("Trainer.Core.Models.Plan", null)
                        .WithMany("Weeks")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Trainer.Core.Models.Plan", b =>
                {
                    b.Navigation("Weeks");
                });
#pragma warning restore 612, 618
        }
    }
}
